name: CI

on:
  workflow_dispatch:
    inputs:
      ansible:
        description: 'Ansible Version'     
        default: 'stable-2.17'
        type: choice
        options: 
        - "stable-2.17"
        - "devel"
      python:
        description: 'Python Version'     
        default: '3.11'
        type: choice
        options: 
        - "3.11"
jobs:
  
###
# Unit tests With Code Coverage
#
# https://docs.ansible.com/ansible/latest/dev_guide/testing_units.html

  unit:
    name: Unit Tests - (Ansible ${{ github.event.inputs.ansible }} Python ${{ github.event.inputs.python }})
    runs-on: ubuntu-latest
    steps:
      - name: Perform unit testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          testing-type: units
          coverage: always
          ansible-core-version: ${{ github.event.inputs.ansible }}
          target-python-version: ${{ github.event.inputs.python }}
